[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "openmed"
version = "0.1.8-rc"
description = "Placeholder package to reserve the name. Real library coming soon."
readme = "README.md"
requires-python = ">=3.6"
license = { text = "MIT" }
authors = [
  { name = "OpenMed Maintainers" }
]

[project.scripts]
openmed = "openmed.cli:main"

[project.optional-dependencies]
dev = [
  "flake8>=7.0",
  "pytest>=7.0",
  "pytest-cov>=4.0"
]

hf = [
  "transformers>=4.40",
  "huggingface-hub>=0.23"
]

[tool.hatch.build]
include = [
  "openmed/**",
  "README.md",
  "pyproject.toml"
]

[tool.hatch.publish.index]
disable = false

[tool.hatch.publish.index.repos]
pypi = { url = "https://upload.pypi.org/legacy/" }

[tool.pytest.ini_options]
markers = [
  "integration: marks end-to-end or external integration tests",
  "slow: marks tests that are expected to run slowly"
]
